language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install: 
  - "pip install pandas"
  - "python setup.py install"
# command to run tests
script: py.test
